name: Collect Token Prices

on:
  schedule:
    # 1분마다 실행 (GitHub Actions는 최소 5분 간격 제한이 있음)
    - cron: '*/5 * * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  collect-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Call Supabase Edge Function
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
      run: |
        curl -X POST "$SUPABASE_URL/functions/v1/collect-prices" \
          -H "Authorization: Bearer $CRON_SECRET" \
          -H "apikey: $SUPABASE_ANON_KEY" \
          -H "Content-Type: application/json" \
          --fail